### ISSUE TITLE
Modify readme.txt to add specs regarding new plugin

### ISSUE THREAD

**Issue by sopu** [loklak/wp-tweets-widget#11]

**Comment by sopu** [comment]
ddf4181 makes desired modifications. Screenshots need to be added.

**Comment by sopu** [comment]
@mariobehling I was hoping to name it 'FA Tweet Widget'

**Comment by mariobehling** [comment]
Please do not include FA. It is not relevant. Can we just name it "Tweets Widget"?

**Comment by sopu** [comment]
436223a  adds the screenshots. Plugin is ready to be added to Wordpress directory. 
Closing this issue!
